# Generated by Django 3.2.9 on 2021-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma',
            name='salary',
            field=models.CharField(default='SOME STRING', max_length=20, verbose_name='доход'),
        ),
    ]
